# labels_vn.py

TRANSLATIONS = {
    # --- TRÁI CÂY (FRUITS) ---
    "king_durian": "sầu riêng ri6",
    "musang_king_durian": "sầu riêng musang king",
    "pomelo_da_xanh": "bưởi da xanh",
    "five_star_pomelo": "bưởi năm roi",
    "hoa_loc_mango": "xoài cát hòa lộc",
    "chu_mango": "xoài cát chu",
    "keo_mango": "xoài keo",
    "dragon_fruit_white": "thanh long ruột trắng",
    "dragon_fruit_red": "thanh long ruột đỏ",
    "yellow_dragon_fruit": "thanh long vàng",
    "mangosteen": "măng cụt",
    "rambutan": "chôm chôm",
    "longan_idoido": "nhãn idoido",
    "longan_xuong_com_vang": "nhãn xuồng cơm vàng",
    "lychee_thieu": "vải thiều lục ngạn",
    "star_apple_lo_ren": "vú sữa lò rèn",
    "guava_taiwan": "ổi đài loan",
    "guava_pink": "ổi xá lị",
    "custard_apple": "na (mãng cầu ta)",
    "soursop": "mãng cầu xiêm",
    "sapodilla": "hồng xiêm",
    "jackfruit_thai": "mít thái",
    "jackfruit_crunchy": "mít dai",
    "avocado_034": "bơ 034",
    "avocado_booth": "bơ booth",
    "passion_fruit": "chanh dây",
    "pomegranate": "lựu",
    "persimmon": "hồng giòn",
    "plum_an_phuoc": "mận an phước",
    "hanoi_plum": "mận hà nội (mận bắc)",
    "star_fruit_sour": "khế chua",
    "star_fruit_sweet": "khế ngọt",
    "ambarella": "cóc",
    "jujube": "táo ta",
    "strawberry_da_lat": "dâu tây đà lạt",
    "mulberry": "dâu tằm",
    "pomelo_nam_roi": "bưởi năm roi",
    "pomelo_da_xanh": "bưởi da xanh",
    "pomelo_dien": "bưởi diễn",
    "pomelo_doan_hung": "bưởi đoan hùng",
    "pomelo_tan_trieu": "bưởi tân triều",
    "orange_sanh": "cam sành",
    "orange_cao_phong": "cam cao phong",
    "orange_vinh": "cam vinh",
    "orange_king": "cam xoàn",
    "mandarin_huong_can": "quýt hương cần",
    "mandarin_cai_be": "quýt hồng cái bè",
    "mango_hoa_loc": "xoài cát hòa lộc",
    "mango_cat_chu": "xoài cát chu",
    "mango_tu_quy": "xoài tứ quý",
    "mango_keo": "xoài keo",
    "mango_uc": "xoài úc",
    "mango_tuong": "xoài tượng",
    "banana_gia": "chuối già hương",
    "banana_su": "chuối sứ (chuối xiêm)",
    "banana_cau": "chuối cau",
    "banana_sap": "chuối sáp",
    "banana_tieu_hong": "chuối tiêu hồng",
    "durian_ri6": "sầu riêng ri6",
    "durian_monthong": "sầu riêng monthong (đô na)",
    "durian_musang_king": "sầu riêng musang king",
    "jackfruit_thai": "mít thái siêu sớm",
    "jackfruit_to_nu": "mít tố nữ",
    "jackfruit_seedless": "mít không hạt",
    "jackfruit_ruot_do": "mít ruột đỏ",
    "dragon_fruit_red": "thanh long ruột đỏ",
    "dragon_fruit_white": "thanh long ruột trắng",
    "dragon_fruit_yellow": "thanh long vàng",
    "longan_idoido": "nhãn idoido",
    "longan_xuong_com_vang": "nhãn xuồng cơm vàng",
    "longan_long": "nhãn lồng hưng yên",
    "lychee_thieu": "vải thiều lục ngạn",
    "lychee_u_hong": "vải u hồng",
    "rambutan_tritrac": "chôm chôm tróc",
    "rambutan_nhan": "chôm chôm nhãn",
    "rambutan_java": "chôm chôm java",
    "guava_nu_hoang": "ổi nữ hoàng",
    "guava_ruby": "ổi ruby không hạt",
    "guava_dong_du": "ổi đông dư",
    "apple_fuji": "táo fuji",
    "apple_envy": "táo envy",
    "apple_gala": "táo gala",
    "apple_green_ninja": "táo xanh ninh thuận",
    "pear_nam_phi": "lê nam phi",
    "pear_mac_cop": "lê mắc cọp",
    "grape_ninh_thuan": "nho đỏ ninh thuận",
    "grape_shine_muscat": "nho mẫu đơn",
    "grape_black_finger": "nho ngón tay",
    "avocado_034": "bơ sáp 034",
    "avocado_booth_7": "bơ booth 7",
    "strawberry_hana": "dâu tây hana",
    "strawberry_new_zealand": "dâu tây new zealand",
    "mangosteen_lai_thieu": "măng cụt lái thiêu",
    "star_apple_lo_ren": "vú sữa lò rèn",
    "star_apple_hoang_kim": "vú sữa hoàng kim",
    "sapodilla_mexico": "hồng xiêm mexico",
    "custard_apple_ba_den": "na núi bà đen",
    "pineapple_queen": "thơm (khóm) queen",
    "pineapple_md2": "dứa mật md2",
    "coconut_xiem": "dừa xiêm bến tre",
    "coconut_dua": "dừa dứa",
    "coconut_sap": "dừa sáp trà vinh",
    "watermelon_khong_hat": "dưa hấu không hạt",
    "watermelon_hac_my_nhan": "dưa hấu hắc mỹ nhân",
    "melon_cantaloupe": "dưa lưới",
    "plum_tam_hoa": "mận tam hoa",
    "plum_hau": "mận hậu sơn la",
    "persimmon_crunchy": "hồng giòn đà lạt",
    "pomegranate_indian": "lựu ấn độ",
    "kiwi_gold": "kiwi vàng",
    "kiwi_green": "kiwi xanh",
    "cherry_red": "anh đào (cherry) đỏ",
    "blueberry": "việt quất",
    "raspberry": "phúc bồn tử",

    # --- RAU CỦ HỮU CƠ (ORGANIC VEGETABLES) ---
    "water_spinach": "rau muống",
    "malabar_spinach": "rau mồng tơi",
    "amaranth": "rau dền",
    "sweet_potato_leaves": "rau lang",
    "pennywort": "rau má",
    "bok_choy": "cải thìa",
    "napa_cabbage": "cải thảo",
    "mustard_greens": "cải bẹ xanh",
    "kale": "cải xoăn",
    "choy_sum": "cải ngọt",
    "cabbage_round": "bắp cải",
    "chives": "hẹ",
    "coriander": "ngò rí",
    "culantro": "ngò gai",
    "thai_basil": "húng quế",
    "mint": "húng lủi",
    "perilla": "tía tô",
    "fish_mint": "diếp cá",
    "bitter_melon": "khổ qua",
    "chayote": "su su",
    "winter_melon": "bí đao",
    "pumpkin_organic": "bí đỏ hồ lô",
    "okra": "đậu bắp",
    "green_bean": "đậu que",
    "asparagus": "măng tây",
    "lotus_root": "ngó sen",
    "bamboo_shoot": "măng tre",
    "water_lily": "bông súng",
    "water_spinach_land": "rau muống cạn",
    "water_spinach_water": "rau muống đồng",
    "malabar_spinach": "rau mồng tơi",
    "amaranth_red": "rau dền đỏ",
    "amaranth_green": "rau dền cơm",
    "bok_choy_organic": "cải thìa hữu cơ",
    "napa_cabbage": "cải thảo",
    "kale_curly": "cải xoăn kale",
    "mustard_greens": "cải bẹ xanh",
    "collard_greens": "cải làn",
    "sweet_potato_leaf": "rau lang",
    "pennywort_small": "rau má lá nhỏ",
    "lettuce_romaine": "xà lách romaine",
    "lettuce_lollo_rossa": "xà lách lollo đỏ",
    "lettuce_iceberg": "xà lách búp (mỡ)",
    "watercress": "xà lách xoong",
    "celery_vietnam": "cần tây đà lạt",
    "coriander": "ngò rí",
    "culantro": "ngò gai",
    "basil_thai": "húng quế",
    "spearmint": "húng lủi",
    "perilla_leaf": "lá tía tô",
    "fish_mint": "rau diếp cá",
    "rice_paddy_herb": "rau ngổ (ngò ôm)",
    "bitter_melon_forest": "khổ qua rừng",
    "bitter_melon_large": "khổ qua trái dài",
    "cucumber_baby": "dưa leo baby",
    "cucumber_japanese": "dưa leo nhật",
    "tomato_beef": "cà chua beef",
    "tomato_cherry": "cà chua bi",
    "tomato_chocolate": "cà chua socola",
    "eggplant_purple": "cà tím dài",
    "eggplant_round": "cà pháo",
    "bell_pepper_red": "ớt chuông đỏ",
    "bell_pepper_yellow": "ớt chuông vàng",
    "chili_bird_eye": "ớt hiểm",
    "chili_horn": "ớt sừng",
    "pumpkin_japanese": "bí đỏ nhật",
    "winter_melon": "bí đao xanh",
    "chayote_fruit": "quả su su",
    "okra_organic": "đậu bắp hữu cơ",
    "asparagus_green": "măng tây xanh",
    "bamboo_shoot_fresh": "măng tươi",
    "lotus_root": "ngó sen",
    "carrot_da_lat": "cà rốt đà lạt",
    "potato_yellow": "khoai tây vàng",
    "sweet_potato_purple": "khoai lang tím",
    "sweet_potato_honey": "khoai lang mật",
    "cassava_root": "củ khoai mì",
    "taro_root": "củ khoai môn",
    "beetroot_organic": "củ dền hữu cơ",
    "kohlrabi": "su hào",
    "radish_white": "củ cải trắng",
    "onion_purple": "hành tây tím",
    "garlic_ly_son": "tỏi lý sơn",
    "ginger_old": "gừng già",
    "turmeric_fresh": "nghệ tươi",

    # --- CỦ & NẤM (ROOTS & MUSHROOMS) ---
    "sweet_potato_yellow": "khoai lang kén",
    "purple_yam": "khoai mỡ",
    "taro": "khoai môn",
    "cassava": "khoai mì",
    "organic_carrot": "cà rốt hữu cơ",
    "daikon_radish": "củ cải trắng",
    "beetroot": "củ dền",
    "kohlrabi": "su hào",
    "ginger": "gừng",
    "turmeric": "nghệ",
    "galangal": "riềng",
    "garlic_ly_son": "tỏi lý sơn",
    "shallot": "hành tím",
    "straw_mushroom": "nấm rơm",
    "oyster_mushroom": "nấm bào ngư",
    "shiitake_mushroom": "nấm hương",
    "wood_ear_mushroom": "mộc nhĩ",
    "king_oyster_mushroom": "nấm đùi gà",
    "enoki_mushroom": "nấm kim châm",

    # --- THỊT, TRỨNG & SỮA (MEAT, EGGS & DAIRY) ---
    "organic_pork_belly": "thịt heo ba chỉ hữu cơ",
    "pork_shoulder": "thịt nạc vai heo",
    "pork_ribs": "sườn non heo",
    "beef_tenderloin": "thăn bò",
    "beef_brisket": "nạm bò",
    "free_range_chicken": "gà ta thả vườn",
    "chicken_breast": "ức gà",
    "chicken_wings": "cánh gà",
    "duck_meat": "thịt vịt",
    "organic_eggs": "trứng gà hữu cơ",
    "salted_duck_eggs": "trứng vịt muối",
    "century_eggs": "trứng bắc thảo",
    "balut": "trứng vịt lộn",
    "fresh_milk_unsweetened": "sữa tươi không đường",
    "yogurt_organic": "sữa chua hữu cơ",
    "pork_belly_organic": "ba chỉ heo hữu cơ",
    "pork_shoulder": "nạc vai heo",
    "pork_loin": "nạc thăn heo",
    "pork_ribs_young": "sườn non heo",
    "pork_leg": "chân giò heo",
    "pork_liver": "gan heo",
    "pork_tongue": "lưỡi heo",
    "beef_steak": "thăn lưng bò (steak)",
    "beef_brisket": "nạm bò",
    "beef_shank": "bắp bò",
    "beef_tenderloin": "thăn nội bò",
    "beef_ribs": "sườn bò",
    "beef_oxtail": "đuôi bò",
    "chicken_whole_free_range": "gà ta nguyên con",
    "chicken_breast": "ức gà",
    "chicken_thigh": "đùi gà",
    "chicken_wings": "cánh gà",
    "chicken_feet": "chân gà",
    "duck_whole": "vịt nguyên con",
    "duck_breast": "ức vịt",
    "goose_meat": "thịt ngỗng",
    "lamb_chops": "sườn cừu",
    "goat_meat": "thịt dê",
    "quail_meat": "thịt chim cút",
    "wild_boar_meat": "thịt lợn rừng",
    "meatball_beef": "bò viên",
    "pork_sausage_vietnam": "giò lụa (chả lụa)",
    "fried_pork_sausage": "chả quế",
    "sour_pork_roll": "nem chua",

    # --- THỦY HẢI SẢN (SEAFOOD) ---
    "black_tiger_shrimp": "tôm sú",
    "white_leg_shrimp": "tôm thẻ",
    "lobster": "tôm hùm",
    "mud_crab": "cua cà mau",
    "flower_crab": "ghẹ xanh",
    "snakehead_fish": "cá lóc",
    "climbing_perch": "cá rô đồng",
    "pangasius_fish": "cá tra / cá ba sa",
    "red_tilapia": "cá điêu hồng",
    "mackerel": "cá thu",
    "tuna": "cá ngừ",
    "squid_tube": "mực ống",
    "cuttlefish": "mực lá",
    "octopus": "bạch tuộc",
    "blood_cockle": "sò huyết",
    "snakehead_fish": "cá lóc đồng",
    "climbing_perch": "cá rô đồng",
    "red_tilapia": "cá điêu hồng",
    "pangasius_catfish": "cá tra / cá basa",
    "catfish_river": "cá trê",
    "carp_fish": "cá chép",
    "grass_carp": "cá trắm cỏ",
    "bronze_featherback": "cá thát lát",
    "mackerel_scad": "cá nục",
    "mackerel_spanish": "cá thu",
    "tuna_ocean": "cá ngừ đại dương",
    "salmon_fillet": "cá hồi fillet",
    "cod_fish": "cá tuyết",
    "anchovy_fresh": "cá cơm tươi",
    "eel_swamp": "lươn đồng",
    "shrimp_black_tiger": "tôm sú",
    "shrimp_white_leg": "tôm thẻ",
    "lobster_spiny": "tôm hùm bông",
    "crayfish": "tôm hùm đất",
    "crab_mud": "cua thịt cà mau",
    "crab_king": "cua hoàng đế",
    "flower_crab": "ghẹ xanh",
    "squid_tube": "mực ống",
    "squid_big": "mực lá",
    "octopus_baby": "bạch tuộc baby",
    "blood_cockle": "sò huyết",
    "oyster_fresh": "hàu sữa",
    "scallop": "cồi sò điệp",
    "snail_apple": "ốc bươu vàng",
    "snail_apple_vietnam": "ốc bươu đen",
    "snail_wool": "ốc len",

    # --- GIA VỊ, ĐỒ KHÔ & KHÁC ---
    "st_25_rice": "gạo st25",
    "sticky_rice": "gạo nếp",
    "brown_rice": "gạo lứt",
    "fish_sauce_phan_thiet": "nước mắm phan thiết",
    "shrimp_paste": "mắm tôm",
    "cashew_nut": "hạt điều",
    "macadamia": "hạt mắc ca",
    "lotus_seed": "hạt sen",
    "black_pepper": "tiêu đen",
    "honey_wild": "mật ong rừng",
    "green_tea_leaves": "lá trà xanh",
    "coffee_bean_robusta": "cà phê robusta",

    # --- CÁC LOẠI GẠO & NGŨ CỐC (RICE & GRAINS) ---
    "st25_rice": "gạo st25 (top 1 thế giới)",
    "st24_rice": "gạo st24",
    "jasmine_rice": "gạo jasmine",
    "huong_lai_rice": "gạo hương lài",
    "nang_hoa_rice": "gạo nàng hoa",
    "nang_sen_rice": "gạo nàng sen",
    "khang_dan_rice": "gạo khang dân",
    "sticky_rice_go_cong": "nếp gò công",
    "sticky_rice_cai_hoa_vang": "nếp cái hoa vàng",
    "red_brown_rice": "gạo lứt huyết rồng",
    "black_brown_rice": "gạo lứt đen",
    "broken_rice": "gạo tấm",
    "glutinous_rice": "gạo nếp",
    "organic_brown_rice": "gạo lứt hữu cơ",

    # --- NƯỚC MẮM (FISH SAUCE) ---
    "fish_sauce_anchovy": "nước mắm cá cơm",
    "fish_sauce_phu_quoc": "nước mắm phú quốc",
    "fish_sauce_phan_thiet": "nước mắm phan thiết",
    "fish_sauce_cat_hai": "nước mắm cát hải",
    "fish_sauce_high_protein": "nước mắm cao đạm",
    "fish_sauce_light": "nước mắm nhĩ",
    "vegetarian_fish_sauce": "nước mắm chay (từ dứa/đậu nành)",

    # --- NƯỚC TƯƠNG, DẦU HÀO, GIA VỊ LỎNG (SAUCES) ---
    "soy_sauce_premium": "nước tương thượng hạng",
    "soy_sauce_garlic_chili": "nước tương tỏi ớt",
    "black_soy_sauce": "hắc xì dầu",
    "oyster_sauce": "dầu hào",
    "oyster_sauce_vegetarian": "dầu hào chay (nấm linh chi)",
    "seasoning_sauce": "nước tương lên men tự nhiên",
    "sweet_sour_fish_sauce": "nước mắm pha sẵn chua ngọt",
    "chili_sauce_muong_khuong": "tương ớt mường khương",
    "chili_sauce_cholimex": "tương ớt (loại phổ thông)",
    "shrimp_paste_sauce": "mắm tôm bắc",
    "seasoning_powder": "hạt nêm",
    "monosodium_glutamate": "bột ngọt (mì chính)",

    # --- ĐỒ UỐNG (BEVERAGES) ---
    "mineral_water": "nước khoáng thiên nhiên",
    "purified_water": "nước tinh khiết",
    "alkaline_water": "nước điện giải kiềm",
    "sparkling_water": "nước khoáng có ga",
    "coconut_water_fresh": "nước dừa tươi",
    "herbal_tea_bottle": "trà thảo mộc đóng chai",
    "green_tea_bottle": "trà xanh đóng chai",
    "roasted_rice_tea": "trà gạo lứt rang",
    "soymilk_organic": "sữa đậu nành hữu cơ",
    "corn_milk": "sữa bắp",
    "lotus_seed_milk": "sữa hạt sen",
    "fruit_juice_orange": "nước ép cam",
    "fruit_juice_guava": "nước ép ổi",
    "energy_drink": "nước tăng lực",
    "electrolyte_drink": "nước bù khoáng (thể thao)",

    # --- CÁC LOẠI DẦU ĂN (COOKING OIL) ---
    "cooking_oil_vegetable": "dầu ăn thực vật",
    "soybean_oil": "dầu đậu nành",
    "sunflower_oil": "dầu hướng dương",
    "rice_bran_oil": "dầu cám gạo",
    "peanut_oil": "dầu phộng (dầu lạc)",
    "sesame_oil": "dầu mè",
    "olive_oil_virgin": "dầu olive nguyên chất",
    "coconut_oil_refined": "dầu dừa luyện",

    # --- CÁC LOẠI ĐẬU & HẠT KHÔ (DRIED BEANS & NUTS) ---
    "black_bean": "đậu đen",
    "red_bean": "đậu đỏ",
    "mung_bean_peeled": "đậu xanh cà vỏ",
    "mung_bean_whole": "đậu xanh nguyên hạt",
    "soybean_seed": "hạt đậu nành",
    "cashew_raw": "hạt điều thô",
    "macadamia_nut": "hạt mắc ca",
    "walnut": "hạt óc chó",
    "chia_seed": "hạt chia",
    "tofu_fresh": "đậu phụ tươi",
    "tofu_fried": "đậu phụ chiên",
    "egg_chicken_organic": "trứng gà hữu cơ",
    "egg_duck": "trứng vịt",
    "egg_quail": "trứng chim cút",
    "egg_salted_duck": "trứng vịt muối",
    "egg_century": "trứng bắc thảo",
    "vermicelli_rice": "bún tươi",
    "pho_noodle_fresh": "bánh phở tươi",
    "instant_noodle": "mì tôm / mì ăn liền",
    "bread_vietnam": "bánh mì việt nam",
    "butter_unsalted": "bơ lạt",
    "cheese_mozzarella": "phô mai mozzarella",
    "yogurt_sweetened": "sữa chua có đường",
    "honey_forest": "mật ong rừng tự nhiên",
    "cashew_roasted": "hạt điều rang muối",
    "macadamia_shelled": "hạt mắc ca tách vỏ",
    "lotus_seed_dried": "hạt sen khô",
    "mushroom_straw": "nấm rơm",
    "mushroom_oyster": "nấm bào ngư",
    "mushroom_shiitake": "nấm hương",
    "mushroom_wood_ear": "nấm mèo (mộc nhĩ)",
    "bird_nest": "yến sào",
    "seaweed_dried": "rong biển khô",

    # --- RAU RỪNG & RAU ĐỊA PHƯƠNG (EXOTIC & LOCAL VEGETABLES) ---
    "wild_leaf_bo_khai": "rau bò khai",
    "wild_leaf_don": "rau dớn (dương xỉ)",
    "wild_leaf_sang": "rau sắng (rau ngót rừng)",
    "wild_leaf_dang": "rau đắng",
    "wild_leaf_cang_cua": "rau càng cua",
    "wild_leaf_dang_bien": "rau muống biển",
    "wild_leaf_sa_nhan": "lá sa nhân",
    "wild_leaf_mac_mat": "lá mắc mật",
    "wild_leaf_cach": "lá cách",
    "wild_leaf_giang": "lá giang",
    "flower_banana": "bắp chuối (hoa chuối)",
    "flower_pumpkin": "bông bí",
    "flower_sesbania_grandiflora": "bông so đũa",
    "flower_sesbania_sesban": "bông điên điển",
    "flower_telosma_cordata": "bông thiên lý",
    "flower_water_lily": "bông súng",
    "bamboo_shoot_bitter": "măng đắng",
    "bamboo_shoot_sweet": "măng ngọt (măng lứa)",

    # --- CÁC LOẠI CỦ & GIA VỊ KHÔ (ROOTS & DRY SPICES) ---
    "turmeric_powder": "tinh bột nghệ",
    "ginger_powder": "bột gừng",
    "garlic_black": "tỏi đen hữu cơ",
    "garlic_one_bulb": "tỏi cô đơn (tỏi một nhánh)",
    "shallot_ly_son": "hành tím lý sơn",
    "cinnamon_stick": "quế thanh",
    "star_anise": "hoa hồi",
    "cardamom_forest": "thảo quả rừng",
    "mac_khen_seeds": "hạt mắc khén",
    "doi_seeds": "hạt dổi",
    "pepper_white": "tiêu sọ (tiêu trắng)",
    "pepper_green_fresh": "tiêu xanh tươi",
    "lemongrass_organic": "sả cây hữu cơ",
    "galangal_root": "củ riềng",
    "sand_ginger": "củ địa liền",

    # --- CÁC LOẠI MẮM & NƯỚC CHẤM ĐẶC SẢN (SPECIALTY SAUCES) ---
    "shrimp_paste_hue": "mắm ruốc huế",
    "shrimp_paste_bac": "mắm tôm bắc",
    "fermented_fish_linh": "mắm cá linh",
    "fermented_fish_sac": "mắm cá sặc",
    "fermented_fish_loc": "mắm cá lóc",
    "fermented_fish_com": "mắm cái (mắm nêm)",
    "fermented_crab_paste": "mắm ba khía",
    "sour_shrimp_hue": "mắm tôm chua huế",
    "chili_salt_tay_ninh": "muối tôm tây ninh",
    "lemon_pepper_salt": "muối tiêu chanh",

    # --- THỦY HẢI SẢN NƯỚC NGỌT (FRESHWATER SEAFOOD) ---
    "fish_linh_young": "cá linh non",
    "fish_com_river": "cá cơm sông",
    "fish_bong_keo": "cá bống kèo",
    "fish_bong_cat": "cá bống cát",
    "fish_hu": "cá hú",
    "fish_lang": "cá lăng",
    "fish_tam": "cá tầm",
    "fish_hoi_sapa": "cá hồi sapa",
    "freshwater_prawn": "tôm càng xanh",
    "field_crab": "cua đồng",
    "field_snail": "ốc nhồi",
    "mud_skipper": "cá thòi lòi",

    # --- THỰC PHẨM KHÔ & CHẾ BIẾN SẴN (DRIED & PROCESSED) ---
    "dried_shrimp_grade_a": "tôm khô loại 1",
    "dried_squid_one_sun": "mực khô một nắng",
    "dried_fish_choke": "khô cá sặc",
    "dried_fish_snakehead": "khô cá lóc",
    "beef_jerky_vietnam": "khô bò miếng",
    "pork_floss": "chà bông heo (ruốc)",
    "chicken_floss_lime_leaf": "khô gà lá chanh",
    "roasted_cashew_shell": "hạt điều rang muối còn vỏ lụa",
    "roasted_peanut": "đậu phộng rang",
    "rice_cracker_saigon": "com cháy chà bông",
    "spring_roll_wrapper": "bánh tráng cuốn chả giò",
    "rice_paper_tay_ninh": "bánh tráng phơi sương tây ninh",

    # --- ĐỒ UỐNG & TRÀ HỮU CƠ (ORGANIC DRINKS & TEA) ---
    "tea_tan_cuong": "trà thái nguyên tân cương",
    "tea_shan_tuyet": "trà shan tuyết cổ thụ",
    "tea_lotus": "trà ướp sen tây hồ",
    "tea_oolong_da_lat": "trà oolong đà lạt",
    "tea_artichoke": "trà atisô",
    "coffee_robusta_dak_lak": "cà phê robusta đắk lắk",
    "coffee_arabica_cau_dat": "cà phê arabica cầu đất",
    "coffee_weasel_premium": "cà phê chồn thượng hạng",
    "herbal_tea_chamomile": "trà hoa cúc",
    "herbal_tea_hibiscus": "trà hoa bụp giấm (atisô đỏ)",

    # --- ĐỒ ĐỘNG HỘP & CHẾ BIẾN (CANNED & PROCESSED) ---
    "canned_sardines": "cá mòi đóng hộp (cá hộp)",
    "canned_tuna": "cá ngừ ngâm dầu",
    "canned_corn": "ngô ngọt đóng hộp",
    "sausage_vissan": "xúc xích tiệt trùng",
    "pork_pate": "pate gan heo",
    "spam_meat": "thịt hộp ham",
    "salted_cashew": "hạt điều rang muối",
    "roasted_almond": "hạnh nhân rang bơ",
    "dried_jackfruit": "mít sấy giòn",
    "dried_banana": "chuối sấy dẻo",
    "lotus_seed_snack": "hạt sen sấy",

    # --- CÁC LOẠI BÁNH KẸO ĐẶC SẢN (SPECIALTY SWEETS) ---
    "pia_cake": "bánh pía sóc trăng",
    "green_bean_cake": "bánh đậu xanh hải dương",
    "coconut_candy": "kẹo dừa bến tre",
    "peanut_candy": "kẹo lạc (kẹo đậu phộng)",
    "sesame_candy": "mè xửng huế",
    "rice_cake_wrapped": "bánh chưng / bánh tét",
    "ramie_leaf_cake": "bánh gai",

    # --- GIA VỊ BỘT & LỎNG BỔ SUNG ---
    "shrimp_salt": "muối tôm",
    "chili_oil": "sa tế tôm",
    "vinegar_apple": "giấm táo",
    "vinegar_rice": "giấm gạo",
    "mayonnaise": "sốt mayonnaise",
    "ketchup": "tương cà",
    "mustard": "mù tạt",
    "curry_powder": "bột cà ri",
    "five_spice_powder": "bột ngũ vị hương",

    # --- CÁC LOẠI NẤM & DƯỢC LIỆU HỮU CƠ ---
    "lingzhi_mushroom": "nấm linh chi",
    "cordyceps": "đông trùng hạ thảo",
    "goji_berry": "kỷ tử",
    "red_jujube": "táo tàu đỏ",
    "lotus_pistil": "tâm sen",
    "artichoke_flower": "hoa atisô tươi",
    "snow_fungus": "nấm tuyết",

    # --- CÁC LOẠI CỦ & QUẢ BỘT (STARCHY VEGETABLES) ---
    "yam_purple": "khoai mỡ",
    "taro_vietnam": "khoai môn cao",
    "sweet_potato_japanese": "khoai lang tím nhật",
    "cassava_fresh": "sắn (khoai mì) tươi",
    "canna_edulis": "củ dong riềng",
    "jicama": "củ đậu (củ sắn)",
    "lotus_seed_fresh": "hạt sen tươi",

    # --- CÁC LOẠI GIA VỊ LỎNG ĐÓNG CHAI (BOTTLED SAUCES) ---
    "soy_sauce_chin_su": "nước tương chinsu",
    "maggi_seasoning": "nước tương maggi",
    "chili_sauce_ly_son": "tương ớt lý sơn",
    "shrimp_satay_oil": "sa tế tôm",
    "vinegar_distilled": "giấm gạo trắng",
    "cooking_wine": "rượu mai quế lộ",
    "sesame_oil_pure": "dầu mè nguyên chất",

    # --- CÁC LOẠI ĐỒ KHÔ TRUYỀN THỐNG (TRADITIONAL DRY FOODS) ---
    "dried_vermicelli": "miến dong",
    "dried_wood_ear": "mộc nhĩ khô",
    "dried_shiitake": "nấm hương khô",
    "rice_paper_thin": "bánh tráng chả giò",
    "dried_lotus_leaf": "lá sen khô",
    "mung_bean_peeled": "đậu xanh cà vỏ",

    # --- CÁC LOẠI TRỨNG & SỮA (EGGS & DAIRY) ---
    "egg_chicken_industrial": "trứng gà công nghiệp",
    "egg_chicken_herb": "trứng gà ta ăn thảo mộc",
    "egg_duck_fresh": "trứng vịt tươi",
    "egg_duck_salted": "trứng vịt muối",
    "egg_quail_fresh": "trứng chim cút",
    "milk_fresh_organic": "sữa tươi hữu cơ",
    "milk_condensed": "sữa đặc có đường",
    "cheese_slice": "phô mai lát",
    "butter_salted": "bơ mặn",

    # --- CÁC LOẠI ĐỒ KHÔ & BÁNH (DRY FOODS & CAKES) ---
    "vermicelli_dried_rice": "bún khô",
    "vermicelli_mung_bean": "miến đậu xanh",
    "rice_paper_baked": "bánh đa (bánh tráng nướng)",
    "shrimp_chips": "bánh phồng tôm",
    "instant_porridge": "cháo ăn liền",
    "cashew_honey": "hạt điều tẩm mật ong",
    "peanut_butter": "bơ đậu phộng",

    # --- RAU GIA VỊ CHI TIẾT (DETAILED HERBS) ---
    "herb_laksa_leaf": "rau răm",
    "herb_knotgrass": "rau đắng",
    "herb_lemon_balm": "kinh giới",
    "herb_elsholtzia": "tía tô",
    "herb_spearmint": "húng lủi",
    "herb_basil": "húng quế",
    "herb_sawtooth": "ngò gai",
    "herb_chives": "hẹ lá",

    # --- THỦY HẢI SẢN CHI TIẾT (MORE SEAFOOD) ---
    "seafood_scallop": "sò điệp",
    "seafood_mussel": "vẹm xanh",
    "seafood_cockle": "sò lông",
    "seafood_sweet_snail": "ốc hương",
    "seafood_squid_dried": "mực khô",
    "seafood_fish_dried": "cá khô",
    "seafood_jellyfish": "sứa biển",

    # --- ĐỒ UỐNG ĐÓNG CHAI (BOTTLED BEVERAGES) ---
    "soft_drink_coke": "nước ngọt coca cola",
    "soft_drink_pepsi": "nước ngọt pepsi",
    "soft_drink_sevenup": "nước ngọt 7up",
    "energy_drink_sting": "nước tăng lực sting đỏ",
    "energy_drink_redbull": "nước tăng lực bò húc",
    "bottled_water_lavie": "nước khoáng lavie",
    "bottled_water_aquafina": "nước tinh khiết aquafina",
    "fruit_juice_vfresh": "nước ép trái cây vfresh",
    "tea_bottled_oolong": "trà ô long đóng chai",
    "tea_bottled_green": "trà xanh không độ",
    "beer_can_tiger": "bia tiger lon",
    "beer_can_heineken": "bia heineken lon",

    # --- BÁNH KẸO & SNACK (SNACKS & CONFECTIONERY) ---
    "snack_potato_lays": "khoai tây chiên lays",
    "snack_shrimp_oishi": "snack tôm oishi",
    "biscuit_oreo": "bánh quy oreo",
    "sponge_cake_chocopie": "bánh chocopie",
    "instant_noodle_hao_hao": "mì hảo hảo tôm chua cay",
    "instant_noodle_omachi": "mì omachi",
    "instant_noodle_kokomi": "mì kokomi",
    "sausage_vissan": "xúc xích vissan",
    "chocolate_bar": "thanh socola",

    # --- CÁC LOẠI GIA VỊ CHI TIẾT KHÁC (MISC GIA VI) ---
    "dipping_sauce_seafood": "nước chấm hải sản (muối ớt xanh)",
    "shrimp_salt_tay_ninh": "muối tôm tây ninh",
    "soup_base_pho": "cốt súp phở",
    "soup_base_bun_bo": "cốt súp bún bò",
    "fried_flour_mix": "bột chiên xù / bột chiên giòn",
    "coconut_milk_canned": "nước cốt dừa đóng hộp",
    "condensed_milk_ong_tho": "sữa đặc ông thọ",

    # --- CÁC LOẠI HẠT GIỐNG (SEEDS - Dành cho shop nông nghiệp) ---
    "seed_tomato": "hạt giống cà chua",
    "seed_chili": "hạt giống ớt",
    "seed_cucumber": "hạt giống dưa leo",
    "seed_water_spinach": "hạt giống rau muống",

    "cardoon": "rau muống (hoặc rau dạng lá dài)",
    "potstickers": "bánh xếp / há cảo",
    "granny_smith": "táo xanh",
    "bell_pepper": "ớt chuông",
    "cucumber": "dưa leo",
    "custard_apple": "mãng cầu ta (na)",
    "head_cabbage": "bắp cải",
    "broccoli": "bông cải xanh",
    "cauliflower": "bông cải trắng",
    "zucchini": "bí ngòi",
}